input_feat_dim: 257   ## Audio feature dimension for 16KHz 
enc_hidden_dim: 64   ## Encoder RNN hidden dimension  128
n_layers_enc: 3   ## Number of Encoder layers  4
vocab_size: 61052        ## VOcabulary size 30
max_out_len: 40       ## Maximum output length
dec_hidden_dim: 128   ## Decoder RNN hidden dimension 256
n_layers_dec: 1       ## Number of decoder layers
sos_id: 1             ## start of sentence ID in vocab
eos_id: 2             ##ENd of sentence ID in vocab
use_gpu: 1
batch_size: 16        #64
num_epochs: 1000
pad_token: 1         #### Check your vocabulary for proper ID